"""Common interface for digital-organism adapters."""
from __future__ import annotations
from typing import Any, Protocol

class OrganismAdapter(Protocol):
    def load(self, config: dict[str, Any]) -> None: ...
    def reset(self, seed: int | None = None) -> None: ...
    def step(self, dt: float) -> None: ...
    def observe(self) -> dict[str, Any]: ...
    def act(self, action: dict[str, Any]) -> None: ...
    def state(self) -> dict[str, Any]: ...
    def metrics(self) -> dict[str, float]: ...
